### ISSUE TITLE
Use Mapbox to send geocode data from frontend?

### ISSUE THREAD

**Issue by fershad** [OpenSpaceData/get.openspacedata.org#1]
**Current**
Currently the backend expects to receive a location name as a string, and will then process that string to get the geocode data for that location.

**Proposed**
Using the [Mapbox API](https://docs.mapbox.com/api/search/geocoding/#data-types) we can give a more structured location search functionality to end-users & send geocoding data to the backend (see snippet below). This will help better guide users (they shouldn't be able to input an invalid location), and will also reduce some load on on the backend. _Users will require internet connection though._

**Example response:**
```json
{
    "id": "place.9911509393291820",
    "type": "Feature",
    "place_type": [
        "region",
        "place"
    ],
    "relevance": 1,
    "properties": {
        "wikidata": "Q1867",
        "short_code": "TW-TPE"
    },
    "text_en-AU": "Taipei",
    "language_en-AU": "en",
    "place_name_en-AU": "Taipei, Taiwan",
    "text": "Taipei",
    "language": "en",
    "place_name": "Taipei, Taiwan",
    "bbox": [
        121.458362004423,
        24.9595340010003,
        121.66602130668,
        25.2091088920745
    ],
    "center": [
        121.63333,
        25.03333
    ],
    "geometry": {
        "type": "Point",
        "coordinates": [
            121.63333,
            25.03333
        ]
    },
    "context": [
        {
            "id": "country.590167737",
            "wikidata": "Q865",
            "short_code": "tw",
            "text_en-AU": "Taiwan",
            "language_en-AU": "en",
            "text": "Taiwan",
            "language": "en"
        }
    ]
}
```

Pricing for the API is here: https://www.mapbox.com/pricing/#geocode (I expect we'd easily be inside the free limit)

**Comment by NiklasJordan** [comment]
Sure, we can use the Mapbox Geocode API. That means that you would request the bbox parameter from the Mapbox Api and send them to the OSD API, right? So the OSD API will get an ready-to-process Bbox and dont have to handle the geocoding?

**Comment by fershad** [comment]
Correct! The frontend would send through the array of Bbox coordinates (anything else required? array format okay?)
```json
"bbox": [
        121.458362004423,
        24.9595340010003,
        121.66602130668,
        25.2091088920745
    ]
```

**Comment by NiklasJordan** [comment]
It's totally fine. Just send in the request the array instead of the string.
`
http://api.openspacedata.org/v1/vegetation-health/ ... &location=[121.458362004423, 24.9595340010003, 121.66602130668, 25.2091088920745]`
