### ISSUE TITLE
Allow responses to be changed

### ISSUE THREAD

**Issue by fershad** [OpenSpaceData/get.openspacedata.org#3]
As the user progresses through the 3 steps (What, Where, When) allow them to go back to a previous step & change their response.

**Comment by NiklasJordan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow responses to be changed](https://trello.com/c/bPk7gyQC/4-allow-responses-to-be-changed)

**Comment by fershad** [comment]
Implemented in https://github.com/OpenSpaceData/get.openspacedata.org/commit/c5ebb5fcb3d23991030dc0b84eaf0b23eb1ffa46
