### ISSUE TITLE
Set latest imagery as default

### ISSUE THREAD

**Issue by NiklasJordan** [OpenSpaceData/get.openspacedata.org#4]
Can we set "Gimme the latest imagery with best quality" on the time range choice as default? This would make the user flow one click faster. What do you think?

![CleanShot 2021-08-02 at 15 27 35](https://user-images.githubusercontent.com/715033/127869712-36742a0f-5ecf-42b3-ac96-9d1d1521a4b4.png)

**Comment by fershad** [comment]
Set latest as the initial value in the store.
Implemented in afb4432ad1c7268348292d922aa6082627d52809
