### ISSUE TITLE
Add more data types in geocoding

### ISSUE THREAD

**Issue by NiklasJordan** [OpenSpaceData/get.openspacedata.org#5]
I've wondered why the location search didn't find my home town 'Schwerin'. Found that mapbox defined multiple data types for the geocoding API: https://docs.mapbox.com/api/search/geocoding/#data-types

Could you accept all types in your geocoding request, pls?

**Comment by NiklasJordan** [comment]
The cool thing is, that it will find then also POIs. Like wildlife parks, landscapes or whatever.

**Comment by fershad** [comment]
Yep, was unsure of how granular we wanted the data to get - added all the types now.
`types: 'country, region, postcode, district, place, locality, neighborhood, address, poi'`

**Comment by fershad** [comment]
Implemented in 3d54a979baf0675263a1ce7da6448e6fba757271
